## **Numpy** 

In [2]:
import numpy as np

In [1]:
mylist = [1, 2, 3, 4]
type(mylist)

list

In [4]:
my_array = np.array(mylist)
type(my_array)


array([1, 2, 3, 4])

In [5]:
my_array

array([1, 2, 3, 4])

## Multi dimensional array

In [7]:
nd_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
nd_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
nd_array.shape

(3, 3)

## arange function

In [13]:
np.arange(0,10) # start from zero,  upto 10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(0,20,2) # generating numbers from 0 to 20 with an interval of 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
# above example using a for loop and range function
for i in range(0,20,2):
  print(i)

0
2
4
6
8
10
12
14
16
18


## Zeroes, ones and eyes

In [17]:
zero = np.zeros(10)  # array of 10 zeros
zero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
np.zeros((10,3))  # array of zeroes with 10 rows, 3 columns

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
np.ones((3,3)) # array of ones with shape3X3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [25]:
np.eye(5,3) # Return a 2-D array with ones on the diagonal and zeros elsewhere.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

**np.identity returns a square matrix** (special case of a 2D-array) which is an identity matrix with the main diagonal (i.e. 'k=0') as 1's and the other values as 0's. you can't change the diagonal k here.

**np.eye returns a 2D-array**, which fills the diagonal, i.e. 'k' which can be set, with 1's and rest with 0's.

So, the main advantage depends on the requirement. If you want an identity matrix, you can go for identity right away, or can call the np.eye leaving the rest to defaults.

But, if you need a 1's and 0's matrix of a particular shape/size or have a control over the diagonal you can go for eye method.

Just like how a matrix is a special case of an array, np.identity is a special case of np.eye.

Additional references:

## Reshape and resize functions

reshape() does not change your data, but resize() does change it. resize() first accommodates all the values in the original array. After that, if extra space is there (or size of new array is greater than original array), it adds its own values.

In [28]:
nd_arr = np.arange(50)
nd_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [29]:
len(nd_arr)

50

In [30]:
nd_arr.reshape(5,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [38]:
nd_arr.shape # shape is still 50,1

(50,)

In [39]:
nd_arr.resize(5,10)

In [41]:
nd_arr.shape  # Here, shape changed to 5X10

(5, 10)

## Linspace function

Returns num evenly spaced samples, calculated over the interval [start, stop].

In [33]:
array1 = np.linspace(0, 7, 10) # 10 numbers equally spaced between 0 and 7
array1

array([0.        , 0.77777778, 1.55555556, 2.33333333, 3.11111111,
       3.88888889, 4.66666667, 5.44444444, 6.22222222, 7.        ])

## Generating random values

numpy.random.randn generates samples from the normal distribution, while numpy.random.rand from a uniform distribution (in the range [0,1)).

#### Using **random.rand** - from a uniform distribution (in the range [0,1))

In [44]:
np.random.rand(5, 3)

array([[0.27687767, 0.16767386, 0.86577541],
       [0.55765826, 0.69075506, 0.95304175],
       [0.01137931, 0.86847017, 0.95711805],
       [0.31139563, 0.38892767, 0.96232739],
       [0.8430824 , 0.9943981 , 0.63905231]])

#### Using **random.randn**   - from a normal distribution

In [45]:
np.random.randn(5, 3)

array([[ 0.74087018,  1.02361436, -0.72072798],
       [-0.13405935, -0.29194405, -0.62861288],
       [ 0.70740716, -1.35202472, -0.15467092],
       [ 0.10547685,  0.93550964, -0.35797154],
       [-0.25308437, -0.1670775 , -1.30471924]])

#### Using **random.randint**  Returns a random integer from low,high interval given

In [48]:
np.random.randint(5, 40)

28

In [49]:
np.random.randint(0, 40, 10) # 10 random numbers between 0 and 40

array([21, 14, 16, 35, 32, 19, 22,  5, 23,  0])

In [50]:
np.random.randint(0, 40, (2,5))

array([[15, 29, 19, 22, 35],
       [ 7,  9, 37, 12, 28]])

## Indexing and slicing

In [52]:
array3 = np.random.randint(0, 40, (5,10))
array3

array([[11,  4, 39, 25,  3, 33,  4, 22, 35, 24],
       [31, 38, 16, 30, 27, 35, 26, 18, 31, 29],
       [ 0, 10, 24, 35, 33, 18,  1,  8, 20, 23],
       [15, 20, 21, 10,  8, 18, 35, 26, 11, 12],
       [25, 37, 17, 15,  2, 10, 34,  5, 20, 32]])

In [53]:
array3[0]

array([11,  4, 39, 25,  3, 33,  4, 22, 35, 24])

In [54]:
array3[0,0]

11

In [56]:
array3[3,5]

18

In [57]:
array3[-1]

array([25, 37, 17, 15,  2, 10, 34,  5, 20, 32])

In [58]:
array3[-1,-1]

32

In [60]:
array3[0,-1]

24

In [62]:
array3[2:6]

array([[ 0, 10, 24, 35, 33, 18,  1,  8, 20, 23],
       [15, 20, 21, 10,  8, 18, 35, 26, 11, 12],
       [25, 37, 17, 15,  2, 10, 34,  5, 20, 32]])

In [63]:
array3[:,2:6]

array([[39, 25,  3, 33],
       [16, 30, 27, 35],
       [24, 35, 33, 18],
       [21, 10,  8, 18],
       [17, 15,  2, 10]])

#### Selective/Conditional indexing

In [65]:
[array3 >10]

[array([[ True, False,  True,  True, False,  True, False,  True,  True,
          True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True,
          True],
        [False, False,  True,  True,  True,  True, False, False,  True,
          True],
        [ True,  True,  True, False, False,  True,  True,  True,  True,
          True],
        [ True,  True,  True,  True, False, False,  True, False,  True,
          True]])]

In [64]:
array3[array3 >10]

array([11, 39, 25, 33, 22, 35, 24, 31, 38, 16, 30, 27, 35, 26, 18, 31, 29,
       24, 35, 33, 18, 20, 23, 15, 20, 21, 18, 35, 26, 11, 12, 25, 37, 17,
       15, 34, 20, 32])

In [67]:
array3[array3 >10] = 100
array3

array([[100,   4, 100, 100,   3, 100,   4, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [  0,  10, 100, 100, 100, 100,   1,   8, 100, 100],
       [100, 100, 100,  10,   8, 100, 100, 100, 100, 100],
       [100, 100, 100, 100,   2,  10, 100,   5, 100, 100]])

## Deep and Shallow copy

In Python, we use = operator to create a copy of an object. You may think that this creates a new object; it doesn't. It only creates a new variable that shares the reference of the original object.

In [72]:
array_new = array1
print(id(array_new), id(array1))

140082393545008 140082393545008


The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy

In [73]:
array_new = array1.copy()
print(id(array_new), id(array1))

140082260105136 140082393545008
